# Generated by Django 2.2 on 2023-06-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CII', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VesselOwnerMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(max_length=255)),
                ('Company_IMO_Number', models.IntegerField()),
                ('Country_Registration', models.CharField(max_length=150)),
                ('Company_Address', models.TextField()),
                ('Company_identification_Number', models.IntegerField()),
                ('Company_Description', models.TextField()),
                ('Add_contact_details', models.CharField(max_length=20)),
            ],
        ),
    ]
