# Generated by Django 2.2 on 2023-06-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CII', '0002_vesselownermaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTypeMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type_name', models.CharField(max_length=255)),
                ('contact_description', models.TextField()),
                ('short_name', models.CharField(max_length=25)),
            ],
        ),
    ]
